package Entity;
// Generated 07-oct-2020 0:02:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleProducto generated by hbm2java
 */
public class DetalleProducto  implements java.io.Serializable {


     private BigDecimal idDetalle;
     private Producto producto;
     private BigDecimal cantidad;

    public DetalleProducto() {
    }

	
    public DetalleProducto(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }
    public DetalleProducto(BigDecimal idDetalle, Producto producto, BigDecimal cantidad) {
       this.idDetalle = idDetalle;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
    public BigDecimal getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


