package Entity;
// Generated 07-oct-2020 0:02:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private BigDecimal idMarca;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Marca() {
    }

	
    public Marca(BigDecimal idMarca) {
        this.idMarca = idMarca;
    }
    public Marca(BigDecimal idMarca, String nombre, Set<Producto> productos) {
       this.idMarca = idMarca;
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public BigDecimal getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(BigDecimal idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


