package Entity;
// Generated 07-oct-2020 0:02:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private BigDecimal idProducto;
     private Marca marca;
     private Imagen imagen;
     private String nomber;
     private String descripcion;
     private String codigoUnico;
     private BigDecimal precio;
     private String modelo;
     private Set<DetalleProducto> detalleProductos = new HashSet<DetalleProducto>(0);

    public Producto() {
    }

	
    public Producto(BigDecimal idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(BigDecimal idProducto, Marca marca, Imagen imagen, String nomber, String descripcion, String codigoUnico, BigDecimal precio, String modelo, Set<DetalleProducto> detalleProductos) {
       this.idProducto = idProducto;
       this.marca = marca;
       this.imagen = imagen;
       this.nomber = nomber;
       this.descripcion = descripcion;
       this.codigoUnico = codigoUnico;
       this.precio = precio;
       this.modelo = modelo;
       this.detalleProductos = detalleProductos;
    }
   
    public BigDecimal getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(BigDecimal idProducto) {
        this.idProducto = idProducto;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public String getNomber() {
        return this.nomber;
    }
    
    public void setNomber(String nomber) {
        this.nomber = nomber;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigoUnico() {
        return this.codigoUnico;
    }
    
    public void setCodigoUnico(String codigoUnico) {
        this.codigoUnico = codigoUnico;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Set<DetalleProducto> getDetalleProductos() {
        return this.detalleProductos;
    }
    
    public void setDetalleProductos(Set<DetalleProducto> detalleProductos) {
        this.detalleProductos = detalleProductos;
    }




}


