package Entity;
// Generated 07-oct-2020 0:02:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private String nombreUsuario;
     private String contrasena;
     private String correo;
     private Character tipoUsuario;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Usuarios() {
    }

	
    public Usuarios(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuarios(BigDecimal idUsuario, String nombreUsuario, String contrasena, String correo, Character tipoUsuario, Set<Cliente> clientes) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.correo = correo;
       this.tipoUsuario = tipoUsuario;
       this.clientes = clientes;
    }
   
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Character getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(Character tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


